### ISSUE TITLE
500 Internal error

### ISSUE THREAD

**Issue by YewTreeHouse** [sredna43/cellarman#9]
Have installed on Pi4B using docker, and tried various locations for .env file.
Run using docker-compose up -d
response = Starting cellarman-main_db_1 ... done
Creating cellarman-main_app_1 ... done

However I keep gettting 500 Internal Error message in the browser - and button for return to Inventory does nothing.

Any ideas?

**Comment by sredna43** [comment]
Hey, thanks for trying this out! It’s been so long since I looked at this, I imagine the install is pretty messy (apologies). I think you’ll want to make sure your docker environment is set up, I’ve had issues using .env files and docker-compose together but can’t remember the magic combination to make it work off the top of my head.

**Comment by sredna43** [comment]
I’ll take a closer look when I get the chance, the installation steps I wrote in the readme are frankly not great.

**Comment by YewTreeHouse** [comment]
Wow - very prompt response, thank you.

**Comment by sredna43** [comment]
I've attached what I believe are the necessary configs below, hopefully this is helpful! I have ORIGIN listed in both configs, and to be perfectly honest I can't remember which one is actually taken when you run this in docker using docker-compose, but let me know if this works for you. Thanks!

`docker-compose.yml`
```yaml
version: '3.8'
services:
  app:
    image: cellarman
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - node-network
    environment:
      - ORIGIN=https://your-domain.com
  db:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge
```

`.env`
```env
MONGO_URL=mongodb://db:27017/cellarman
ORIGIN=https://your-domain.com
```
